# Generated by Django 4.0 on 2023-01-28 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=220, unique=True)),
                ('date_issued', models.DateField()),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=20)),
                ('VAT_percentage', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('invoice_due_date', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField()),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier', to='suppliers.supplier')),
            ],
        ),
    ]
