# Generated by Django 4.0 on 2023-01-29 20:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lossgainreason',
            name='loss_or_gain',
            field=models.CharField(choices=[('loss', 'loss'), ('gain', 'gain')], default='loss', max_length=220),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_item', to='suppliers.purchaseinvoice'),
        ),
    ]
