# Generated by Django 4.0 on 2023-01-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_lossgainreason_loss_or_gain_stockitem_in_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='manual_stock_update',
        ),
        migrations.AddField(
            model_name='manualstockupdate',
            name='stock_affected',
            field=models.ManyToManyField(blank=True, null=True, related_name='manual_update', to='stock.StockItem'),
        ),
    ]
