# Generated by Django 4.0 on 2023-01-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stockitem_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualstockupdate',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='manualstockupdate',
            name='stock_affected',
            field=models.ManyToManyField(blank=True, related_name='manual_update', to='stock.StockItem'),
        ),
    ]
