# Generated by Django 4.0 on 2023-01-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_manualstockupdate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manualstockupdate',
            name='confirm_called_police',
            field=models.BooleanField(blank=True, null=True, verbose_name='For dangerous species it is obligatory to report incident to Police'),
        ),
    ]
