# Generated by Django 4.0 on 2023-01-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stockitem_in_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='order',
        ),
        migrations.AlterField(
            model_name='manualstockupdate',
            name='confirm_called_police',
            field=models.BooleanField(blank=True, null=True, verbose_name='Confirm, called police: for dangerous species it is obligatory to report incident to Police'),
        ),
    ]
