# Generated by Django 4.0 on 2023-01-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_stockitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='sale_price',
        ),
    ]
