# Generated by Django 4.1.5 on 2023-01-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=220, unique=True)),
                ('date_issued', models.DateField()),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=20)),
                ('VAT_percentage', models.IntegerField()),
                ('suplier_name', models.CharField(max_length=220, unique=True)),
                ('delivery_date', models.DateField()),
                ('invoice_due_date', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField()),
            ],
        ),
    ]
