# Generated by Django 4.0 on 2023-01-29 00:06

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnviromentRequirements',
            new_name='Enviroment',
        ),
        migrations.AddField(
            model_name='species',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='species', to='species.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='enviroment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='species', to='species.enviroment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='species', to='species.size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True),
        ),
    ]
