# Generated by Django 4.0 on 2023-01-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_rename_enviromentrequirements_enviroment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
    ]
