# Generated by Django 4.0 on 2023-01-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_alter_category_options_alter_species_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
