# Generated by Django 4.0 on 2023-01-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customerorder_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='reference_code',
            field=models.CharField(max_length=220, unique=True),
        ),
    ]
